apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: api-gateway
  labels:
    stage: config
type: Opaque
stringData:
  ENC_KEY: social-network-secret-key
  JWT_KEY: social-network-secret-key  
  PASSWORD_SECRET: social-network-secret-key
