apiVersion: v1
kind: Secret
metadata:
  name: live-secret
  namespace: live
  labels:
    stage: config
type: Opaque
stringData:
  ENC_KEY: social-network-secret-key
  JWT_KEY: social-network-secret-key
