apiVersion: v1
kind: Service
metadata:
  name: live
  namespace: live
  labels:
    stage: app
spec:
  selector:
    app: live
  ports:
    - name: client
      port: 8082
      targetPort: 8082
  type: ClusterIP