apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-frontend
  namespace: frontend
  labels:
    stage: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: frontend.social.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs-frontend
                port:
                  number: 80
