apiVersion: v1
kind: Service
metadata:
  name: nextjs-frontend
  namespace: frontend
  labels:
    stage: app
spec:
  selector:
    app: nextjs-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
