apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-traces-pvc
  namespace: monitoring
  labels:
    stage: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi