apiVersion: v1
kind: Service
metadata:
  name: victoria-logs
  namespace: monitoring
  labels:
    stage: monitoring
spec:
  selector:
    app: victoria-logs
  ports:
    - protocol: TCP
      port: 9428
      targetPort: 9428
  type: ClusterIP