apiVersion: v1
kind: Service
metadata:
  name: victoria-traces
  namespace: monitoring
  labels:
    app: victoria-traces
    stage: monitoring
spec:
  selector:
    app: victoria-traces
  ports:
    - protocol: TCP
      port: 10428
      targetPort: 10428
  type: ClusterIP